# お知らせ君設定ファイル
---
title: "お知らせ君"
control:
  # local or remote
  type: local
  # remote 失敗時にfallbackするかどうか
  fallback: true
  # remoteのconfigファイルへのパス
  remote: http://ctl.example.jp/oshirasekun.yml
admin:
  password: admin
startScreen:
  auth:
    required: true
    # ldap, ad, mount, web, command, dummy
    # ldap, ad … LDAPまたはADの認証を行う。
    # mount … pathにマウントまたは接続を行う。
    # web … 特定サイトにWeb認証する。BASIC認証のみ対応。
    # command … コマンドを実行する。コマンドが成功すれば良い。
    # dummy … ユーザ名とパスワードが同じなら何でも通るテスト用のダミー
    method: dummy
    # Handlebarsを使用する。エスケープ処理は行わない。
    path: //fs.example.jp/{{username}}$
    # 将来的には何をエスケープするのかマップで指定したいけど、まだできない。
    escapeMap: {}
    option:
      sleep: 10
      drive: Z
      domain: localnet
  news:
    show: true
    # plain, html, markdown, asciidoc(未実装), review(未実装)
    type: markdown
    # UTF-8以外は現在サポートしていない
    encode: UTF-8
    # このファイルからの相対パス、または絶対パスやURL
    path: ./oshirasekun.md
