# お知らせ君設定ファイル
---
control:
  # remoteはまだ
  type: local
  fallback: local
admin:
  password: admin
startScreen:
  auth:
    require: true
    # ldap, ad, mount, web, command, dummy
    # ldap, ad … LDAPまたはADの認証を行う。
    # mount … pathにマウントまたは接続を行う。
    # web … 特定サイトにWeb認証する。BASIC認証のみ対応。
    # command … コマンドを実行する。コマンドが成功すれば良い。
    # dummy … ユーザ名とパスワードが同じなら何でも通るテスト用のダミー
    method: dummy
    # Handlebarsを使用する。エスケープ処理は行わない。
    path: //fs.example.jp/{{username}}$
    # 将来的には何をエスケープするのかマップで指定したいけど、まだできない。
    escapeMap: {}
    option:
      drive: Z
      domain: localnet
  news:
    show: true
    # plain, markdown, gfm, [asciidoc, review, textile, html]
    type: markdown
    # UTF-8以外は現在サポートしていない
    encode: UTF-8
    # このファイルからの相対パス、または絶対パスやURL
    path: ./oshirasekun.md
